# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvPnNfWLQkqYhkkqNpyQkBGjayDp_ei_
"""



import streamlit as st
import cv2
import numpy as np
from PIL import Image

# Title and description
st.title("Cartoonify Your Image 🎨")
st.write("Upload an image to see the cartoon effect.")

# Image uploader
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Load and preprocess image
    image = Image.open(uploaded_file)
    img = np.array(image)

    # Resize and convert to grayscale
    img = cv2.resize(img, (600, 600))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Apply median blur and edge detection
    gray_blur = cv2.medianBlur(gray, 5)
    edges = cv2.adaptiveThreshold(
        gray_blur, 255,
        cv2.ADAPTIVE_THRESH_MEAN_C,
        cv2.THRESH_BINARY,
        blockSize=9,
        C=9
    )

    # Apply bilateral filter for cartoon effect
    color = cv2.bilateralFilter(img, d=9, sigmaColor=300, sigmaSpace=300)
    cartoon = cv2.bitwise_and(color, color, mask=edges)

    # Display result
    st.image(cartoon, caption="Cartoonified Image", use_column_width=True)

